[streamlit_config]
STREAMLIT_SERVER_COOKIE_SECRET = "your-secret-key"
STREAMLIT_SERVER_PORT = "8501"
STREAMLIT_SERVER_BASE_URL = "https://your-app-name.herokuapp.com"
STREAMLIT_SERVER_MAX_UPLOAD_SIZE = "your-max-upload-size"
STREAMLIT_SERVER_MAX_THREADS = "your-max-threads"


[MySQLcredentials]
host = "your-hostname"
users_dbname = "your-usersdb-name"
data_dbname = "your-datadb-name"
user = "your-username"
password = "your-password"
